### ISSUE TITLE
Reload scrollable on resize

### ISSUE THREAD

**Issue by hirethisdeveloper** [gigerbytes/angular-sly#3]
In order to get a horizontal sly to readjust and show the correct active item when you resize your browser you need to reload the sly object with the keyword reload. Sly will then perform new calculations on the list items appropriately.

Add this to your horizontal and horizontal repeat, saved me on a project.

$(window).on("resize", function() { frame.sly("reload"); });

**Comment by gigerbytes** [comment]
Added, thank you!
